### ISSUE TITLE
[7.9.0] error: constructor DynamicFontModule in class DynamicFontModule cannot be applied to given types;       new DynamicFontModule()

### ISSUE THREAD

**Issue by efstathiosntonas** [wix/react-native-ui-lib#2764]
## Description

After updating to `7.9.0` Android build throws this error: 

```
> Task :app:compileDebugJavaWithJavac FAILED
xxxxx/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:222: error: constructor DynamicFontModule in class DynamicFontModule cannot be applied to given types;
      new DynamicFontModule(),
      ^
  required: ReactApplicationContext
  found:    no arguments
  reason: actual and formal argument lists differ in length
Note: xxxxx/android/app/src/main/java/com/hiki/MainApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

offending PR: https://github.com/wix/react-native-ui-lib/pull/2736

![Screenshot 2023-10-12 at 11 08 20](https://github.com/wix/react-native-ui-lib/assets/717975/8522496c-3713-4da5-a95b-6e45c3f1c325)

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Environment

- React Native version: 0.72.5 Paper
- React Native UI Lib version: 7.9.0

### Affected platforms

- [x] Android
- [ ] iOS
- [ ] Web

**Comment by jax-okvip** [comment]
same issue

**Comment by jbagaresgaray** [comment]
same issue 

```
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 71.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
    Watchman: 2023.10.09.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.13.0 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 23.0, iOS 17.0, macOS 14.0, tvOS 17.0, watchOS 10.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10671973
    Xcode: 15.0/15A240d - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.8.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: ^0.71.0 => 0.71.14 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

![image](https://github.com/wix/react-native-ui-lib/assets/3625802/b4436d34-bca5-401c-8257-d72e57ecf48f)

**Comment by ChrisPam** [comment]
I'm having this issue too

**Comment by baveku** [comment]
Five hours, I tried to find out what I was wrong. How can we fix it?

**Comment by ChrisPam** [comment]
@baveku I just reverted to "react-native-ui-lib": "7.2.1" and now it's working and eas build is working correctly

**Comment by jbagaresgaray** [comment]
Yes downgrading to `7.8.0` will resolved the issue. I encourage anyone who encounter this issue to just downgrade and update your package.json to that specific version.

**Comment by thanhloc-17** [comment]
same issues

**Comment by ethanshar** [comment]
@M-i-k-e-l 
Can you take a look?

**Comment by M-i-k-e-l** [comment]
Fixed in version `7.9.1`
